number_of_vehicles: 100
number_of_walkers: 0
display_size: 256
max_past_step: 1
dt: 0.05 # Check fixed delta step time in carla_ros_bridge
discrete: false
discrete_acc: [-3.0, 0.0, 3.0]
discrete_steer: [-0.2, 0.0, 0.2]
continuous_accel_range: [-3.0, 3.0]
continuous_steer_range: [-0.3, 0.3]
ego_vehicle_filter: vehicle.lincoln*
port: 2000
town: Town05
task_mode: random
max_time_episode: 1000
max_waypt: 12
obs_range: 32
lidar_bin: 0.125
d_behind: 12
out_lane_thres: 2.0
desired_speed: 8
max_ego_spawn_times: 200
display_route: true
pixor_size: 64
pixor: false
